### ISSUE TITLE
shorter email addresses

### ISSUE THREAD

**Issue by r10s** [deltachat/mailadm#1]
the currently generated burner-email-addresses have the format `tmpx_4422832084233920@domain`, which seems to be a bit long for many input field and places typically email-addresses are shown, see images below.

while this could be fixed, the long names also have the disadvantage that they cannot be compared easily and typing them is hard.

i suggest to change the address to sth. as `tmp.1234abcd@domain` - so just a hex-represenation of a 32bit value. this way, there is a chance to compare things and event to type them in.

i would also prefer `tmp.` over `tmp_` - it is easier to type and is maybe more expected and just looks better :)

maybe things could be even shorter, sth. as `tmp.a7x45` with  34^5 states (omitting 0 and O) = 4.5 millions, should be random enough as well.

<img width="320" alt="Screen Shot 2020-02-17 at 15 10 40" src="https://user-images.githubusercontent.com/9800740/74661295-f6c15b80-5197-11ea-90f3-b41f15aa19c7.png">

<img src=https://user-images.githubusercontent.com/9800740/74661268-e610e580-5197-11ea-97ac-315be2602e88.jpg width=320>

**Comment by Simon-Laux** [comment]
you can even go up to to Base32 IMO

**Comment by hpk42** [comment]
k -- if you in exchange allow android users to choose a nickname easily, we have a deal :)

**Comment by r10s** [comment]
i think using 5 characters from the set `2345789acdefghijkmnpqrstuvwxyz` would be awesome - the set omits characters easily confused while with 2^30 there are still about 24 millions different addresses. 

> k -- if you in exchange allow android users to choose a nickname easily, we have a deal :)

deal!
