### ISSUE TITLE
Update https://mailadm.readthedocs.io/

### ISSUE THREAD

**Issue by link2xt** [deltachat/mailadm#130]
The website is not updated and I do not have access to the organization on readthedocs.

PR #129 got merged, but the website is still out of date.

cc @missytake @hpk42 who has access to the website?

**Comment by hpk42** [comment]
On Wed, Sep 27, 2023 at 13:25 -0700, link2xt wrote:
> The website is not updated and do not have access to the organization on readthedocs.
> 
> PR #129 got merged, but the website is still out of date.
> 
> cc @missytake @hpk42 who has access to the website?

seems it belongs to me -- link2xt, missytake, i invited you to the readthedocs mailadm project. 
let me know if the usernames fit ;)

**Comment by hpk42** [comment]
seems rtd projects need a configuration file: 
https://docs.readthedocs.io/en/stable/config-file/v2.html
