### ISSUE TITLE
Move README.txt from sysconfig to .rst documentation

### ISSUE THREAD

**Issue by link2xt** [deltachat/mailadm#19]
It would be nice to have all the documentation, including nginx integration etc. available in one place, at https://mailadm.readthedocs.io/, so it can be read as a whole prior to installing anything.

Currently `README.txt` it is stored in the mailadm user directory with placeholders substituted with the current setup variables.

**Comment by missytake** [comment]
As there is much less documentation needed now, all of it actually moved to the readthedocs page.
