### ISSUE TITLE
errors should be json, too

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/mailadm#28]
see https://github.com/deltachat/deltachat-desktop/issues/2671

**Comment by missytake** [comment]
What format does make sense for this?

```json
{
  'type': 'error',
  'reason': 'invalid token',  # 'token not specified', 'user already exists', 'internal server error'
  'status code': 403, # 403, 409, 500
}
```

We don't really need additional data. We could even leave the status code out of the json, as its already in the HTTP response, but maybe that makes it easier for some client function.

**Comment by Simon-Laux** [comment]
> What format does make sense for this?

whatever format we implement in core for this, what you proposed looks good enough. though I would do `status_code` instead of the whitespace, spaces in property names are not very nice (even though there are ways to make it work)
