### ISSUE TITLE
Allow running mailadm without root privs

### ISSUE THREAD

**Issue by hpk42** [deltachat/mailadm#3]
Right now, mailadm runs as the root user which is ungood. 

We rather want to document how to setup a mailadm user, configure permissions and restrict "sudo" access to only allow reloading dovecot/postfix services.

**Comment by zagy** [comment]
One issue is that postmap drops its privileges to the uid/gid of the source file, even when run as root. So the user writing the file needs be able to write the hash, too.

**Comment by hpk42** [comment]
this is done now, all mailadm state resides in the sqlite database in ~mailadm/mailadm.db by default (you can change with env var MAILADM_DB)
